version: "3"
services:
  db:
    image: mdillon/postgis
    ports: 
    - "9432:5432"
  node:
    build:
      context: .
      dockerfile: Dockerfile-setup
    volumes:
      - .:/usr/src/app
    command: /bin/bash
  redis:
    image: redis
    ports: 
      - "6379:6379"
  tile-server:
    build: .
    command: npm run start-development
    links:
      - db
      - redis
    depends_on: # Express dependency between services
      - db 
      - redis
    volumes:
      - .:/usr/src/app
    ports: 
      - "8081:8081"
