version: "3"
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile-setup
    volumes:
      - .:/usr/src/app
    command: /bin/bash
  redis:
    image: redis
    ports: 
      - "6379:6379"
  tile-server:
    build: .
    env_file: .env
    command: npm run start-development
    depends_on: # Express dependency between services
      - redis
    volumes:
      - .:/usr/src/app
      # - /usr/src/app/node_modules
    ports: 
      - "8081:8081"
    links:
      - redis
